package openapi

import (
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/matjeroapps/admin/internal/contracts"
	"github.com/matjeroapps/admin/internal/coreclient"
)

func BuildAdminSpec() (*openapi3.T, error) {
	return BuildDocument(DocumentSpec{
		Title:         "Matjero Admin API",
		Description:   "OpenAPI contract for the Matjero Admin API.",
		Authenticated: true,
		Tags:          CommonTags(),
		Routes:        append(ActorRoutes(true), adminRoutes()...),
	})
}

func adminRoutes() []RouteSpec {
	return []RouteSpec{
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/overview",
			OperationID: "getAdminOverview",
			Summary:     "Get platform overview",
			Description: "Returns high-level counts for major commerce aggregates.",
			Tags:        []string{"Audit"},
			Auth:        true,
			Responses: []ResponseSpec{
				OKResponse("Platform overview", contracts.CountResponse{}),
				ErrorResponse(http.StatusUnauthorized, "Unauthorized"),
				ErrorResponse(http.StatusForbidden, "Forbidden"),
				ErrorResponse(http.StatusInternalServerError, "Internal error"),
			},
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/suppliers",
			OperationID: "listAdminSuppliers",
			Summary:     "List suppliers",
			Tags:        []string{"Suppliers"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.Supplier]("Supplier collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/suppliers/{id}/status",
			OperationID: "updateAdminSupplierStatus",
			Summary:     "Update a supplier status",
			Tags:        []string{"Suppliers", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Supplier identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Supplier status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/sellers",
			OperationID: "listAdminSellers",
			Summary:     "List sellers",
			Tags:        []string{"Sellers"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.Seller]("Seller collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/sellers/{id}/status",
			OperationID: "updateAdminSellerStatus",
			Summary:     "Update a seller status",
			Tags:        []string{"Sellers", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Seller identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Seller status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/stores",
			OperationID: "listAdminStores",
			Summary:     "List stores",
			Tags:        []string{"Stores"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.Store]("Store collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/stores/{id}/status",
			OperationID: "updateAdminStoreStatus",
			Summary:     "Update a store status",
			Tags:        []string{"Stores", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Store identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Store status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/products",
			OperationID: "listAdminProducts",
			Summary:     "List products",
			Tags:        []string{"Catalog", "Attributes", "Variants", "SKUs"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.Product]("Product collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/products/{id}/status",
			OperationID: "updateAdminProductStatus",
			Summary:     "Update a product status",
			Tags:        []string{"Catalog", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Product identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Product status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/categories",
			OperationID: "listAdminCategories",
			Summary:     "List categories",
			Tags:        []string{"Categories"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.Category]("Category collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/categories/{id}/status",
			OperationID: "updateAdminCategoryStatus",
			Summary:     "Update a category status",
			Tags:        []string{"Categories", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Category identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Category status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/offers",
			OperationID: "listAdminSupplierOffers",
			Summary:     "List supplier offers",
			Tags:        []string{"Supplier Offers"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam(), StringParam("market_code", "Filter by market code", false)},
			Responses:   ListResponses[coreclient.SupplierCatalogItem]("Supplier offer collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/offers/{id}/status",
			OperationID: "updateAdminOfferStatus",
			Summary:     "Update a supplier offer status",
			Tags:        []string{"Supplier Offers", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Supplier offer identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Supplier offer status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/listings",
			OperationID: "listAdminSellerListings",
			Summary:     "List seller listings",
			Tags:        []string{"Seller Listings"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam(), StringParam("store_id", "Filter by store identifier", false)},
			Responses:   ListResponses[coreclient.SellerListing]("Seller listing collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/listings/{id}/status",
			OperationID: "updateAdminListingStatus",
			Summary:     "Update a seller listing status",
			Tags:        []string{"Seller Listings", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Seller listing identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Seller listing status updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/admin/locations",
			OperationID: "listAdminFulfillmentLocations",
			Summary:     "List fulfillment locations",
			Tags:        []string{"Fulfillment Locations"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam(), StringParam("supplier_id", "Filter by supplier identifier", false)},
			Responses:   ListResponses[coreclient.FulfillmentLocation]("Fulfillment location collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/admin/locations/{id}/status",
			OperationID: "updateAdminLocationStatus",
			Summary:     "Update a fulfillment location status",
			Tags:        []string{"Fulfillment Locations", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Fulfillment location identifier")},
			RequestBody: contracts.StatusUpdateRequest{},
			Responses:   AuthOKResponses("Fulfillment location status updated", contracts.StatusResponse{}),
		},
	}
}
